# Spring config
logging.level.ash.java.nzfforganiser: ${LOG_LEVEL:INFO}
server.port: ${PORT:5000}

# App config
nzff.path: "/2019/auckland/wishlist/"
nzff.baseUrl: "https://www.nziff.co.nz"

nzff.wishlistCacheConfig:
  expireSec: 30
  maxSize: 100

nzff.sessionCacheConfig:
  expireSec: 3600 # 1 hour
  maxSize: 100