# Spring config
logging.level.ash.java.nzfforganiser: ${LOG_LEVEL:INFO}

server.port: ${PORT:5000}

spring.profiles.active: ${SPRING_PROF:dev}

# App config
nzffPath: "/2018/auckland/wishlist/"
nzffBase: "https://www.nziff.co.nz"

wishlistCacheConfig:
  expireSec: 30
  maxSize: 100

sessionCacheConfig:
  expireSec: 14400 # 4 hours
  maxSize: 100