# Spring config
logging.level.ash.java.nzfforganiser: ${LOG_LEVEL:INFO}

server.port: ${PORT:5000}

spring.profiles.active: ${SPRING_PROF:dev}

# App config
nzff.path: "/2018/auckland/wishlist/"
nzff.baseUrl: "https://www.nziff.co.nz"

nzff.wishlistCacheConfig:
  expireSec: 30
  maxSize: 100

nzff.sessionCacheConfig:
  expireSec: 14400 # 4 hours
  maxSize: 100